services:
  schweinehund:
    image: ghcr.io/rouhim/schweinehund
    build:
      dockerfile: Containerfile.local
      context: .
    user: "1000:1000"
    volumes:
      - ./data:/data:U
    environment:
      - DATABASE_URL=sqlite:/data/schweinehund.db
    ports:
      - "9666:9666"
